### ISSUE TITLE
Remove IMASdd dependency

### ISSUE THREAD

**Issue by orso82** [ProjectTorreyPines/RABBIT.jl#2]
@adrianaghiozzi `IMASdd` seems to be imported but not used... am I wrong? Can we then remove it as a dependency?

**Comment by adrianaghiozzi** [comment]
Just removed it in this commit: https://github.com/ProjectTorreyPines/RABBIT.jl/commit/3a6f0321321cc222c9430edaf21112f76aa16716 
Do I now need to change the version number in the Project.toml/do any other steps to make sure these changes are picked up in the registry?

**Comment by orso82** [comment]
you should be able to do
```
make register_patch repo=RABBIT
```
in the FUSE directory and that should take care of everything
